import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { connectDB } from '../config/db.js';
import { PatientModel } from '../models/Patient.js';
import { VisitModel } from '../models/Visit.js';
import { LabReportModel } from '../models/LabReport.js';
import { ConsentModel } from '../models/Consent.js';
import { AppointmentModel } from '../models/Appointment.js';

dotenv.config();

const SEED_PATIENTS = [
  {
    name: 'Aarav Sharma',
    age: 48,
    gender: 'Male',
    phone: '+91 98765 43210',
    email: 'aarav.sharma@example.com',
    bloodGroup: 'B+',
    abhaId: '91-4567-8901-2345',
    abhaAddress: 'aarav.sharma@abdm',
    address: 'Flat 402, Green Meadows Apt, Indiranagar, Bengaluru, Karnataka - 560038',
    emergencyContact: {
      name: 'Meera Sharma',
      relationship: 'Spouse',
      phone: '+91 98765 43211',
    },
    allergies: [
      {
        substance: 'Penicillin & Amoxicillin',
        severity: 'Severe',
        reaction: 'Anaphylactic reaction & severe urticaria',
        recordedDate: '2023-04-12',
      },
      {
        substance: 'Iodinated Radiocontrast Media',
        severity: 'Moderate',
        reaction: 'Cutaneous flushing and localized pruritus',
        recordedDate: '2024-01-15',
      },
    ],
    medicalHistory: [
      {
        condition: 'Type 2 Diabetes Mellitus',
        diagnosedYear: '2019',
        status: 'Active',
        notes: 'Managed with oral hypoglycemics and lifestyle modifications',
      },
      {
        condition: 'Essential Hypertension',
        diagnosedYear: '2021',
        status: 'Controlled',
        notes: 'Well-controlled with ARB (Telmisartan 40mg)',
      },
    ],
    registeredDate: '2023-01-10',
    lastVisitDate: '2026-08-28',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Priya Patel',
    age: 34,
    gender: 'Female',
    phone: '+91 97654 32109',
    email: 'priya.patel@example.com',
    bloodGroup: 'O+',
    abhaId: '92-8921-3456-7890',
    abhaAddress: 'priya.patel@abdm',
    address: 'B-12, Shanti Niketan, Ellisbridge, Ahmedabad, Gujarat - 380006',
    emergencyContact: {
      name: 'Kunal Patel',
      relationship: 'Brother',
      phone: '+91 97654 32108',
    },
    allergies: [
      {
        substance: 'Sulfonamides (Sulfa drugs)',
        severity: 'Moderate',
        reaction: 'Maculopapular rash on trunk and arms',
        recordedDate: '2022-09-18',
      },
    ],
    medicalHistory: [
      {
        condition: 'Primary Hypothyroidism',
        diagnosedYear: '2020',
        status: 'Controlled',
        notes: 'Daily Levothyroxine 50 mcg on empty stomach',
      },
      {
        condition: 'Iron Deficiency Anemia',
        diagnosedYear: '2024',
        status: 'In Remission',
        notes: 'Completed 3-month oral ferrous ascorbate course',
      },
    ],
    registeredDate: '2023-05-14',
    lastVisitDate: '2026-08-30',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Rajesh Iyer',
    age: 62,
    gender: 'Male',
    phone: '+91 96543 21098',
    email: 'rajesh.iyer@example.com',
    bloodGroup: 'A+',
    abhaId: '91-3344-5566-7788',
    abhaAddress: 'rajesh.iyer@abdm',
    address: 'Plot 88, 4th Main, Anna Nagar West, Chennai, Tamil Nadu - 600040',
    emergencyContact: {
      name: 'Lakshmi Iyer',
      relationship: 'Spouse',
      phone: '+91 96543 21097',
    },
    allergies: [
      {
        substance: 'Aspirin & NSAIDs',
        severity: 'Severe',
        reaction: 'Gastric irritation and bronchospasm episodes',
        recordedDate: '2021-11-03',
      },
    ],
    medicalHistory: [
      {
        condition: 'Coronary Artery Disease (CAD - Post PTCA)',
        diagnosedYear: '2022',
        status: 'Active',
        notes: 'Stent placed in LAD; regular cardiology reviews',
      },
      {
        condition: 'Mixed Dyslipidemia',
        diagnosedYear: '2018',
        status: 'Controlled',
        notes: 'Atorvastatin 20mg at bedtime',
      },
      {
        condition: 'Stage 1 Hypertension',
        diagnosedYear: '2016',
        status: 'Controlled',
        notes: 'Amlodipine 5mg OD',
      },
    ],
    registeredDate: '2022-11-20',
    lastVisitDate: '2026-09-02',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Sunita Verma',
    age: 29,
    gender: 'Female',
    phone: '+91 95432 10987',
    email: 'sunita.verma@example.com',
    bloodGroup: 'AB+',
    abhaId: '93-1122-3344-5566',
    abhaAddress: 'sunita.verma@abdm',
    address: 'Tower 5, Eco City, Sector 78, Noida, Uttar Pradesh - 201301',
    emergencyContact: {
      name: 'Amit Verma',
      relationship: 'Spouse',
      phone: '+91 95432 10986',
    },
    allergies: [],
    medicalHistory: [
      {
        condition: 'Gestational Diabetes Mellitus (GDM)',
        diagnosedYear: '2026',
        status: 'Active',
        notes: '28 weeks gestation; dietary management with self-monitoring of blood glucose',
      },
    ],
    registeredDate: '2026-03-10',
    lastVisitDate: '2026-09-01',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Mohammad Ali',
    age: 55,
    gender: 'Male',
    phone: '+91 94321 09876',
    email: 'm.ali@example.com',
    bloodGroup: 'O-',
    abhaId: '91-7788-9900-1122',
    abhaAddress: 'm.ali@abdm',
    address: 'H.No 14-2-89, Banjara Hills Road No. 12, Hyderabad, Telangana - 500034',
    emergencyContact: {
      name: 'Fatima Ali',
      relationship: 'Daughter',
      phone: '+91 94321 09875',
    },
    allergies: [
      {
        substance: 'Diclofenac',
        severity: 'Moderate',
        reaction: 'Angioedema and facial swelling',
        recordedDate: '2023-08-11',
      },
    ],
    medicalHistory: [
      {
        condition: 'Chronic Kidney Disease (CKD Stage 2)',
        diagnosedYear: '2024',
        status: 'Active',
        notes: 'eGFR 68 mL/min; microalbuminuria monitoring every 6 months',
      },
      {
        condition: 'Uncontrolled Hypertension',
        diagnosedYear: '2019',
        status: 'Active',
        notes: 'Dual therapy with Telmisartan + Chlorthalidone',
      },
    ],
    registeredDate: '2024-02-18',
    lastVisitDate: '2026-08-25',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Ananya Sen',
    age: 19,
    gender: 'Female',
    phone: '+91 93210 98765',
    email: 'ananya.sen@example.com',
    bloodGroup: 'A-',
    abhaId: '94-5566-7788-9900',
    abhaAddress: 'ananya.sen@abdm',
    address: 'Flat 3C, Lake Gardens View, Kolkata, West Bengal - 700045',
    emergencyContact: {
      name: 'Debashis Sen',
      relationship: 'Father',
      phone: '+91 93210 98764',
    },
    allergies: [
      {
        substance: 'Peanuts & Tree Nuts',
        severity: 'Life-Threatening',
        reaction: 'Severe anaphylaxis with acute airway obstruction; carries EpiPen',
        recordedDate: '2015-06-20',
      },
      {
        substance: 'Dust Mites & Animal Dander',
        severity: 'Mild',
        reaction: 'Allergic rhinitis and conjunctivitis',
        recordedDate: '2020-03-10',
      },
    ],
    medicalHistory: [
      {
        condition: 'Moderate Persistent Bronchial Asthma',
        diagnosedYear: '2016',
        status: 'Active',
        notes: 'Budesonide/Formoterol inhaler twice daily + SOS Levosalbutamol',
      },
    ],
    registeredDate: '2025-01-20',
    lastVisitDate: '2026-08-20',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
];

async function seedDatabase() {
  try {
    const connected = await connectDB();
    if (!connected) {
      console.log('Skipping MongoDB seed as database is offline.');
      process.exit(0);
    }

    console.log('🧹 Clearing existing collections...');
    await PatientModel.deleteMany({});
    await VisitModel.deleteMany({});
    await LabReportModel.deleteMany({});
    await ConsentModel.deleteMany({});
    await AppointmentModel.deleteMany({});

    console.log('🌱 Seeding Patients...');
    const insertedPatients = await PatientModel.insertMany(SEED_PATIENTS);
    const aarav = insertedPatients[0];
    const priya = insertedPatients[1];
    const rajesh = insertedPatients[2];
    const sunita = insertedPatients[3];
    const ali = insertedPatients[4];
    const ananya = insertedPatients[5];

    console.log('🌱 Seeding Visits & Consultations...');
    await VisitModel.insertMany([
      {
        patientId: aarav._id,
        patientName: aarav.name,
        doctorName: 'Dr. Sarah Rao, MD',
        doctorSpecialty: 'Cardiologist & General Physician',
        clinicOrHospital: 'MedIndia Apex Care Clinic, Bengaluru',
        date: '2026-08-28',
        visitType: 'Follow-up',
        chiefComplaint: 'Quarterly diabetic checkup, reports mild morning fatigue and occasional post-prandial heaviness',
        symptoms: ['Mild fatigue', 'Post-meal heaviness', 'Occasional dry mouth'],
        vitals: {
          bloodPressure: '128/82 mmHg',
          heartRate: 74,
          temperature: 98.4,
          spO2: 99,
          respiratoryRate: 16,
          weight: 76.5,
          height: 174,
          bmi: 25.3,
        },
        clinicalExamination: 'Chest clear bilaterally, S1 S2 heard normal. Pedal edema absent. Peripheral pulses palpable.',
        diagnosis: 'Type 2 Diabetes Mellitus (Suboptimally Controlled) with Stage 1 Hypertension',
        icd10Code: 'E11.69',
        clinicalNotes: 'HbA1c has shown a mild upward drift to 7.8%. Blood pressure is reasonably controlled at 128/82. Adjusted Metformin dosage.',
        prescriptions: [
          {
            medicineName: 'Metformin Sustained Release',
            dosage: '1000 mg',
            frequency: '1-0-1 (Morning & Night)',
            timing: 'After Food',
            duration: '90 Days',
            instructions: 'Take immediately after principal meals',
          },
          {
            medicineName: 'Telmisartan Tablets',
            dosage: '40 mg',
            frequency: '1-0-0 (Morning)',
            timing: 'Before Food',
            duration: '90 Days',
            instructions: 'Take every morning at the same time',
          },
          {
            medicineName: 'Empagliflozin (Jardiance)',
            dosage: '10 mg',
            frequency: '1-0-0 (Morning)',
            timing: 'With Food',
            duration: '90 Days',
            instructions: 'Ensure adequate daily water intake (>2.5 liters)',
          },
        ],
        orderedLabTests: ['HbA1c & Fasting Plasma Glucose', 'Serum Creatinine & eGFR', 'Lipid Profile - Comprehensive'],
        followUpDate: '2026-11-28',
        status: 'Completed',
      },
      {
        patientId: aarav._id,
        patientName: aarav.name,
        doctorName: 'Dr. Ramesh Kulkarni, MD',
        doctorSpecialty: 'Endocrinologist',
        clinicOrHospital: 'City Endocrine Care, Bengaluru',
        date: '2026-05-15',
        visitType: 'Specialist Consultation',
        chiefComplaint: 'Review of glycemic variations and diet plan evaluation',
        symptoms: ['Afternoon lethargy'],
        vitals: {
          bloodPressure: '132/86 mmHg',
          heartRate: 78,
          temperature: 98.6,
          spO2: 98,
          weight: 78.0,
          height: 174,
          bmi: 25.8,
        },
        clinicalExamination: 'No acanthosis nigricans. Fundus examination within normal limits.',
        diagnosis: 'Type 2 Diabetes Mellitus without complications',
        icd10Code: 'E11.9',
        clinicalNotes: 'Encouraged continuous glucose monitoring trial. Emphasized avoidance of late-night snacks.',
        prescriptions: [
          {
            medicineName: 'Metformin SR',
            dosage: '500 mg',
            frequency: '1-0-1',
            timing: 'After Food',
            duration: '90 Days',
            instructions: 'Regular meals schedule',
          },
        ],
        orderedLabTests: ['HbA1c', 'Urine Microalbumin'],
        followUpDate: '2026-08-20',
        status: 'Completed',
      },
      {
        patientId: rajesh._id,
        patientName: rajesh.name,
        doctorName: 'Dr. Sarah Rao, MD',
        doctorSpecialty: 'Cardiologist',
        clinicOrHospital: 'MedIndia Apex Care Clinic, Bengaluru',
        date: '2026-09-02',
        visitType: 'Specialist Consultation',
        chiefComplaint: 'Routine post-PTCA cardiology evaluation. Reports no chest pain, shortness of breath, or palpitations on climbing 2 flights of stairs.',
        symptoms: [],
        vitals: {
          bloodPressure: '122/78 mmHg',
          heartRate: 68,
          temperature: 98.4,
          spO2: 99,
          respiratoryRate: 15,
          weight: 69.0,
          height: 168,
          bmi: 24.4,
        },
        clinicalExamination: 'Normal S1, S2 with no murmurs or gallops. Lungs clear to auscultation.',
        diagnosis: 'Atherosclerotic Heart Disease of Native Coronary Artery (Post-PCI)',
        icd10Code: 'I25.10',
        clinicalNotes: 'Patient doing excellently post stent placement in 2022. ECG today confirms normal sinus rhythm without ischemic changes. Lipids well controlled on statin therapy.',
        prescriptions: [
          {
            medicineName: 'Clopidogrel (Plavix)',
            dosage: '75 mg',
            frequency: '0-1-0 (Noon)',
            timing: 'After Food',
            duration: '180 Days',
            instructions: 'Antiplatelet therapy - Note: Patient allergic to Aspirin!',
          },
          {
            medicineName: 'Atorvastatin Tablets',
            dosage: '20 mg',
            frequency: '0-0-1 (Night)',
            timing: 'After Food',
            duration: '180 Days',
            instructions: 'Take at bedtime',
          },
          {
            medicineName: 'Metoprolol Succinate ER',
            dosage: '25 mg',
            frequency: '1-0-0 (Morning)',
            timing: 'After Food',
            duration: '180 Days',
            instructions: 'Monitor pulse rate periodically',
          },
        ],
        orderedLabTests: ['12-Lead Electrocardiogram (ECG)', 'Lipid Profile', 'Liver Function Tests'],
        followUpDate: '2027-03-02',
        status: 'Completed',
      },
      {
        patientId: priya._id,
        patientName: priya.name,
        doctorName: 'Dr. Sarah Rao, MD',
        doctorSpecialty: 'General Physician',
        clinicOrHospital: 'MedIndia Apex Care Clinic, Bengaluru',
        date: '2026-08-30',
        visitType: 'Routine Checkup',
        chiefComplaint: 'Evaluation of thyroid function and general wellness checkup',
        symptoms: ['Occasional mild hair loss', 'Mild cold intolerance in winter'],
        vitals: {
          bloodPressure: '116/74 mmHg',
          heartRate: 72,
          temperature: 98.2,
          spO2: 99,
          weight: 58.5,
          height: 162,
          bmi: 22.3,
        },
        clinicalExamination: 'Thyroid gland non-tender, no palpable nodules. Skin texture normal.',
        diagnosis: 'Hypothyroidism, Unspecified (Euthyroid on Replacement Therapy)',
        icd10Code: 'E03.9',
        clinicalNotes: 'TSH is well within target range at 2.1 mIU/L. Hemoglobin has recovered to 13.2 g/dL. Continue current Levothyroxine dose.',
        prescriptions: [
          {
            medicineName: 'Levothyroxine Sodium',
            dosage: '50 mcg',
            frequency: '1-0-0 (Morning)',
            timing: 'Before Food',
            duration: '180 Days',
            instructions: 'Take first thing in the morning with a full glass of water. Wait 45 mins before tea/breakfast.',
          },
        ],
        orderedLabTests: ['Thyroid Profile (Free T3, Free T4, TSH)'],
        followUpDate: '2027-02-28',
        status: 'Completed',
      },
    ]);

    console.log('🌱 Seeding Lab Reports...');
    await LabReportModel.insertMany([
      {
        patientId: aarav._id,
        patientName: aarav.name,
        testName: 'Glycated Hemoglobin (HbA1c) & Fasting Plasma Glucose',
        category: 'Biochemistry',
        orderedByDoctor: 'Dr. Sarah Rao, MD',
        labName: 'MedIndia Central Diagnostics, NABL Accredited',
        sampleCollectionDate: '2026-08-28',
        reportDate: '2026-08-29',
        parameters: [
          {
            name: 'HbA1c (Glycated Hb)',
            value: '7.8',
            unit: '%',
            referenceRange: '< 5.7 (Normal), 5.7-6.4 (Prediabetes), >=6.5 (Diabetes)',
            isAbnormal: true,
          },
          {
            name: 'Estimated Average Glucose (eAG)',
            value: '177',
            unit: 'mg/dL',
            referenceRange: '70 - 126',
            isAbnormal: true,
          },
          {
            name: 'Fasting Blood Glucose',
            value: '142',
            unit: 'mg/dL',
            referenceRange: '70 - 99',
            isAbnormal: true,
          },
          {
            name: 'Post-Prandial Glucose (2h)',
            value: '198',
            unit: 'mg/dL',
            referenceRange: '< 140',
            isAbnormal: true,
          },
        ],
        overallResult: 'Elevated HbA1c (7.8%) indicating suboptimally controlled Type 2 Diabetes.',
        status: 'Abnormal',
        remarks: 'Recommend pharmacological titration and dietary carbohydrate restriction.',
      },
      {
        patientId: aarav._id,
        patientName: aarav.name,
        testName: 'Renal Function Panel & eGFR',
        category: 'Biochemistry',
        orderedByDoctor: 'Dr. Sarah Rao, MD',
        labName: 'MedIndia Central Diagnostics, NABL Accredited',
        sampleCollectionDate: '2026-08-28',
        reportDate: '2026-08-29',
        parameters: [
          {
            name: 'Serum Creatinine',
            value: '0.95',
            unit: 'mg/dL',
            referenceRange: '0.70 - 1.20',
            isAbnormal: false,
          },
          {
            name: 'Blood Urea Nitrogen (BUN)',
            value: '15.2',
            unit: 'mg/dL',
            referenceRange: '7.0 - 20.0',
            isAbnormal: false,
          },
          {
            name: 'eGFR (CKD-EPI Formula)',
            value: '94',
            unit: 'mL/min/1.73m²',
            referenceRange: '> 90 (Normal renal function)',
            isAbnormal: false,
          },
          {
            name: 'Serum Uric Acid',
            value: '5.8',
            unit: 'mg/dL',
            referenceRange: '3.5 - 7.2',
            isAbnormal: false,
          },
        ],
        overallResult: 'Normal kidney function parameters with preserved glomerular filtration rate.',
        status: 'Normal',
        remarks: 'Renal profile suitable for SGLT-2 inhibitor therapy.',
      },
      {
        patientId: rajesh._id,
        patientName: rajesh.name,
        testName: 'Comprehensive Lipid Profile',
        category: 'Biochemistry',
        orderedByDoctor: 'Dr. Sarah Rao, MD',
        labName: 'Apex Heart Diagnostics, Bengaluru',
        sampleCollectionDate: '2026-09-01',
        reportDate: '2026-09-02',
        parameters: [
          {
            name: 'Total Cholesterol',
            value: '148',
            unit: 'mg/dL',
            referenceRange: '< 200',
            isAbnormal: false,
          },
          {
            name: 'LDL Cholesterol',
            value: '64',
            unit: 'mg/dL',
            referenceRange: '< 70 (High Risk CAD target)',
            isAbnormal: false,
          },
          {
            name: 'HDL Cholesterol',
            value: '46',
            unit: 'mg/dL',
            referenceRange: '> 40',
            isAbnormal: false,
          },
          {
            name: 'Triglycerides',
            value: '138',
            unit: 'mg/dL',
            referenceRange: '< 150',
            isAbnormal: false,
          },
        ],
        overallResult: 'Optimal lipid control achieved on Atorvastatin 20mg (LDL < 70 mg/dL target met).',
        status: 'Normal',
        remarks: 'Continue current statin therapy.',
      },
      {
        patientId: priya._id,
        patientName: priya.name,
        testName: 'Thyroid Function Panel (FT3, FT4, TSH)',
        category: 'Biochemistry',
        orderedByDoctor: 'Dr. Sarah Rao, MD',
        labName: 'MedIndia Central Diagnostics',
        sampleCollectionDate: '2026-08-30',
        reportDate: '2026-08-30',
        parameters: [
          {
            name: 'Thyroid Stimulating Hormone (TSH)',
            value: '2.14',
            unit: 'mIU/L',
            referenceRange: '0.40 - 4.50',
            isAbnormal: false,
          },
          {
            name: 'Free Triiodothyronine (FT3)',
            value: '3.1',
            unit: 'pg/mL',
            referenceRange: '2.0 - 4.4',
            isAbnormal: false,
          },
          {
            name: 'Free Thyroxine (FT4)',
            value: '1.28',
            unit: 'ng/dL',
            referenceRange: '0.82 - 1.77',
            isAbnormal: false,
          },
        ],
        overallResult: 'Euthyroid state maintained on current Levothyroxine replacement dose.',
        status: 'Normal',
        remarks: 'Repeat panel in 6 months.',
      },
      {
        patientId: ali._id,
        patientName: ali.name,
        testName: 'Urine Microalbumin & Serum Creatinine',
        category: 'Biochemistry',
        orderedByDoctor: 'Dr. Sarah Rao, MD',
        labName: 'NephroCare Diagnostic Center',
        sampleCollectionDate: '2026-08-24',
        reportDate: '2026-08-25',
        parameters: [
          {
            name: 'Serum Creatinine',
            value: '1.48',
            unit: 'mg/dL',
            referenceRange: '0.70 - 1.20',
            isAbnormal: true,
          },
          {
            name: 'eGFR',
            value: '58',
            unit: 'mL/min/1.73m²',
            referenceRange: '> 90',
            isAbnormal: true,
          },
          {
            name: 'Urine Albumin-to-Creatinine Ratio (UACR)',
            value: '88',
            unit: 'mg/g',
            referenceRange: '< 30 (Microalbuminuria: 30-300)',
            isAbnormal: true,
          },
        ],
        overallResult: 'Mildly elevated serum creatinine with moderate microalbuminuria (CKD Stage 3a transition).',
        status: 'Abnormal',
        remarks: 'Requires strict blood pressure target < 130/80 mmHg and nephrology follow-up.',
      },
    ]);

    console.log('🌱 Seeding Consents...');
    await ConsentModel.insertMany([
      {
        patientId: aarav._id,
        patientName: aarav.name,
        patientAbhaId: aarav.abhaId,
        requesterName: 'Dr. Sarah Rao (MedIndia Apex Care)',
        requesterType: 'Doctor',
        purpose: 'Care Management',
        dataTypes: ['EHR / Consultations', 'Prescriptions', 'Diagnostic Lab Reports'],
        permissionMode: 'VIEW',
        dateFrom: '2026-01-01',
        dateTo: '2027-01-01',
        expiryDate: '2027-01-01',
        status: 'GRANTED',
        grantedAt: new Date().toISOString(),
        signatureMock: 'ABDM-MOCK-SIG-98a1f7c3e4b2d9',
      },
      {
        patientId: aarav._id,
        patientName: aarav.name,
        patientAbhaId: aarav.abhaId,
        requesterName: 'Apollo Tele-Specialty Network (HIU)',
        requesterType: 'HIU',
        purpose: 'Second Opinion',
        dataTypes: ['Diagnostic Lab Reports', 'Prescriptions'],
        permissionMode: 'VIEW',
        dateFrom: '2026-08-01',
        dateTo: '2026-09-30',
        expiryDate: '2026-09-30',
        status: 'GRANTED',
        grantedAt: new Date().toISOString(),
        signatureMock: 'ABDM-MOCK-SIG-55f2c1a89b03d4',
      },
      {
        patientId: rajesh._id,
        patientName: rajesh.name,
        patientAbhaId: rajesh.abhaId,
        requesterName: 'Dr. Sarah Rao (MedIndia Apex Care)',
        requesterType: 'Doctor',
        purpose: 'Care Management',
        dataTypes: ['EHR / Consultations', 'Prescriptions', 'Diagnostic Lab Reports'],
        permissionMode: 'VIEW',
        dateFrom: '2026-01-01',
        dateTo: '2027-01-01',
        expiryDate: '2027-01-01',
        status: 'GRANTED',
        grantedAt: new Date().toISOString(),
        signatureMock: 'ABDM-MOCK-SIG-11928374a5b6c7',
      },
      {
        patientId: priya._id,
        patientName: priya.name,
        patientAbhaId: priya.abhaId,
        requesterName: 'ThyroCare Diagnostic Network',
        requesterType: 'Diagnostic Lab',
        purpose: 'Diagnostic Review',
        dataTypes: ['Diagnostic Lab Reports'],
        permissionMode: 'STORE',
        dateFrom: '2026-08-01',
        dateTo: '2026-11-01',
        expiryDate: '2026-11-01',
        status: 'GRANTED',
        grantedAt: new Date().toISOString(),
        signatureMock: 'ABDM-MOCK-SIG-44a33d22e11f00',
      },
    ]);

    console.log('🌱 Seeding Appointments...');
    await AppointmentModel.insertMany([
      {
        patientId: aarav._id,
        patientName: aarav.name,
        patientAge: aarav.age,
        patientGender: aarav.gender,
        doctorName: 'Dr. Sarah Rao',
        specialty: 'Cardiologist & General Physician',
        date: '2026-09-05',
        timeSlot: '09:30 AM',
        type: 'In-Person Consultation',
        status: 'In-Progress',
        tokenNumber: 1,
        reason: 'Diabetic routine follow-up & HbA1c review',
      },
      {
        patientId: rajesh._id,
        patientName: rajesh.name,
        patientAge: rajesh.age,
        patientGender: rajesh.gender,
        doctorName: 'Dr. Sarah Rao',
        specialty: 'Cardiologist & General Physician',
        date: '2026-09-05',
        timeSlot: '10:15 AM',
        type: 'In-Person Consultation',
        status: 'Waiting',
        tokenNumber: 2,
        reason: 'Post-PTCA cardiac checkup & ECG review',
      },
      {
        patientId: sunita._id,
        patientName: sunita.name,
        patientAge: sunita.age,
        patientGender: sunita.gender,
        doctorName: 'Dr. Sarah Rao',
        specialty: 'Cardiologist & General Physician',
        date: '2026-09-05',
        timeSlot: '11:00 AM',
        type: 'In-Person Consultation',
        status: 'Scheduled',
        tokenNumber: 3,
        reason: 'Gestational blood sugar monitoring review',
      },
      {
        patientId: priya._id,
        patientName: priya.name,
        patientAge: priya.age,
        patientGender: priya.gender,
        doctorName: 'Dr. Sarah Rao',
        specialty: 'Cardiologist & General Physician',
        date: '2026-09-05',
        timeSlot: '02:30 PM',
        type: 'Video Follow-up',
        status: 'Scheduled',
        tokenNumber: 4,
        reason: 'Thyroid function test follow-up',
      },
      {
        patientId: ali._id,
        patientName: ali.name,
        patientAge: ali.age,
        patientGender: ali.gender,
        doctorName: 'Dr. Sarah Rao',
        specialty: 'Cardiologist & General Physician',
        date: '2026-09-05',
        timeSlot: '04:00 PM',
        type: 'In-Person Consultation',
        status: 'Scheduled',
        tokenNumber: 5,
        reason: 'Renal function and BP medication titration',
      },
    ]);

    console.log('✅ Database seeded successfully with realistic healthcare records!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
}

seedDatabase();
